[project]
name = "ollama-autogen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogen-agentchat>=0.5.5",
    "autogen-ext[ollama,openai]>=0.5.5",
    "elevenlabs>=1.57.0",
    "pydantic>=2.11.4",
    "python-dotenv>=1.1.0",
    "requests>=2.32.3",
]
